<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AddonSettingsSeeder extends Seeder
{
    public function run(): void
    {
        $settings = [
            [
                'id' => '070c6bbd-d777-11ed-96f4-0c7a158e4469',
                'key_name' => 'twilio',
                'live_values' => '{"gateway":"twilio","mode":"live","status":"0","sid":"data","messaging_service_sid":"data","token":"data","from":"data","otp_template":"data"}',
                'test_values' => '{"gateway":"twilio","mode":"live","status":"0","sid":"data","messaging_service_sid":"data","token":"data","from":"data","otp_template":"data"}',
                'settings_type' => 'sms_config',
                'mode' => 'live',
                'is_active' => 0,
                'created_at' => null,
                'updated_at' => '2023-08-12 07:01:29',
                'additional_data' => null,
            ],
            [
                'id' => '070c766c-d777-11ed-96f4-0c7a158e4469',
                'key_name' => '2factor',
                'live_values' => '{"gateway":"2factor","mode":"live","status":"0","api_key":"data"}',
                'test_values' => '{"gateway":"2factor","mode":"live","status":"0","api_key":"data"}',
                'settings_type' => 'sms_config',
                'mode' => 'live',
                'is_active' => 0,
                'created_at' => null,
                'updated_at' => '2023-08-12 07:01:36',
                'additional_data' => null,
            ],
            [
                'id' => '0d8a9308-d6a5-11ed-962c-0c7a158e4469',
                'key_name' => 'mercadopago',
                'live_values' => '{"gateway":"mercadopago","mode":"test","status":"0","access_token":"data","public_key":"data"}',
                'test_values' => '{"gateway":"mercadopago","mode":"test","status":"0","access_token":"data","public_key":"data"}',
                'settings_type' => 'payment_config',
                'mode' => 'test',
                'is_active' => 0,
                'created_at' => null,
                'updated_at' => '2023-08-27 11:57:11',
                'additional_data' => '{"gateway_title":null,"gateway_image":"2023-04-12-64367be3b7b6a.png"}',
            ],
            [
                'id' => '0d8a9e49-d6a5-11ed-962c-0c7a158e4469',
                'key_name' => 'liqpay',
                'live_values' => '{"gateway":"liqpay","mode":"test","status":"0","private_key":"data","public_key":"data"}',
                'test_values' => '{"gateway":"liqpay","mode":"test","status":"0","private_key":"data","public_key":"data"}',
                'settings_type' => 'payment_config',
                'mode' => 'test',
                'is_active' => 0,
                'created_at' => null,
                'updated_at' => '2023-08-12 06:32:31',
                'additional_data' => '{"gateway_title":null,"gateway_image":""}',
            ],
            [
                'id' => '101befdf-d44b-11ed-8564-0c7a158e4469',
                'key_name' => 'paypal',
                'live_values' => '{"gateway":"paypal","mode":"test","status":"0","client_id":"data","client_secret":"data"}',
                'test_values' => '{"gateway":"paypal","mode":"test","status":"0","client_id":"data","client_secret":"data"}',
                'settings_type' => 'payment_config',
                'mode' => 'test',
                'is_active' => 0,
                'created_at' => null,
                'updated_at' => '2023-08-30 03:41:32',
                'additional_data' => '{"gateway_title":null,"gateway_image":""}',
            ],
            [
                'id' => '133d9647-cabb-11ed-8fec-0c7a158e4469',
                'key_name' => 'hyper_pay',
                'live_values' => '{"gateway":"hyper_pay","mode":"test","status":"0","entity_id":"data","access_code":"data"}',
                'test_values' => '{"gateway":"hyper_pay","mode":"test","status":"0","entity_id":"data","access_code":"data"}',
                'settings_type' => 'payment_config',
                'mode' => 'test',
                'is_active' => 0,
                'created_at' => null,
                'updated_at' => '2023-08-12 06:32:42',
                'additional_data' => '{"gateway_title":null,"gateway_image":""}',
            ],
            [
                'id' => '1821029f-d776-11ed-96f4-0c7a158e4469',
                'key_name' => 'msg91',
                'live_values' => '{"gateway":"msg91","mode":"live","status":"0","template_id":"data","auth_key":"data"}',
                'test_values' => '{"gateway":"msg91","mode":"live","status":"0","template_id":"data","auth_key":"data"}',
                'settings_type' => 'sms_config',
                'mode' => 'live',
                'is_active' => 0,
                'created_at' => null,
                'updated_at' => '2023-08-12 07:01:48',
                'additional_data' => null,
            ],
            [
                'id' => '18210f2b-d776-11ed-96f4-0c7a158e4469',
                'key_name' => 'nexmo',
                'live_values' => '{"gateway":"nexmo","mode":"live","status":"0","api_key":"","api_secret":"","token":"","from":"","otp_template":""}',
                'test_values' => '{"gateway":"nexmo","mode":"live","status":"0","api_key":"","api_secret":"","token":"","from":"","otp_template":""}',
                'settings_type' => 'sms_config',
                'mode' => 'live',
                'is_active' => 0,
                'created_at' => null,
                'updated_at' => '2023-04-10 02:14:44',
                'additional_data' => null,
            ],
            [
                'id' => '18fbb21f-d6ad-11ed-962c-0c7a158e4469',
                'key_name' => 'foloosi',
                'live_values' => '{"gateway":"foloosi","mode":"test","status":"0","merchant_key":"data"}',
                'test_values' => '{"gateway":"foloosi","mode":"test","status":"0","merchant_key":"data"}',
                'settings_type' => 'payment_config',
                'mode' => 'test',
                'is_active' => 0,
                'created_at' => null,
                'updated_at' => '2023-08-12 06:34:33',
                'additional_data' => '{"gateway_title":null,"gateway_image":""}',
            ],
            [
                'id' => '2767d142-d6a1-11ed-962c-0c7a158e4469',
                'key_name' => 'paytm',
                'live_values' => '{"gateway":"paytm","mode":"test","status":"0","merchant_key":"data","merchant_id":"data","merchant_website_link":"data"}',
                'test_values' => '{"gateway":"paytm","mode":"test","status":"0","merchant_key":"data","merchant_id":"data","merchant_website_link":"data"}',
                'settings_type' => 'payment_config',
                'mode' => 'test',
                'is_active' => 0,
                'created_at' => null,
                'updated_at' => '2023-08-22 06:30:55',
                'additional_data' => '{"gateway_title":null,"gateway_image":""}',
            ],
            [
                'id' => '3201d2e6-c937-11ed-a424-0c7a158e4469',
                'key_name' => 'amazon_pay',
                'live_values' => '{"gateway":"amazon_pay","mode":"test","status":"0","pass_phrase":"data","access_code":"data","merchant_identifier":"data"}',
                'test_values' => '{"gateway":"amazon_pay","mode":"test","status":"0","pass_phrase":"data","access_code":"data","merchant_identifier":"data"}',
                'settings_type' => 'payment_config',
                'mode' => 'test',
                'is_active' => 0,
                'created_at' => null,
                'updated_at' => '2023-08-12 06:36:07',
                'additional_data' => '{"gateway_title":null,"gateway_image":""}',
            ],
            [
                'id' => '4593b25c-d6a1-11ed-962c-0c7a158e4469',
                'key_name' => 'paytabs',
                'live_values' => '{"gateway":"paytabs","mode":"test","status":"0","profile_id":"data","server_key":"data","base_url":"data"}',
                'test_values' => '{"gateway":"paytabs","mode":"test","status":"0","profile_id":"data","server_key":"data","base_url":"data"}',
                'settings_type' => 'payment_config',
                'mode' => 'test',
                'is_active' => 0,
                'created_at' => null,
                'updated_at' => '2023-08-12 06:34:51',
                'additional_data' => '{"gateway_title":null,"gateway_image":""}',
            ],
            [
                'id' => '4e9b8dfb-e7d1-11ed-a559-0c7a158e4469',
                'key_name' => 'bkash',
                'live_values' => '{"gateway":"bkash","mode":"test","status":"0","app_key":"data","app_secret":"data","username":"data","password":"data"}',
                'test_values' => '{"gateway":"bkash","mode":"test","status":"0","app_key":"data","app_secret":"data","username":"data","password":"data"}',
                'settings_type' => 'payment_config',
                'mode' => 'test',
                'is_active' => 0,
                'created_at' => null,
                'updated_at' => '2023-08-12 06:39:42',
                'additional_data' => '{"gateway_title":null,"gateway_image":""}',
            ],
            [
                'id' => '544a24a4-c872-11ed-ac7a-0c7a158e4469',
                'key_name' => 'fatoorah',
                'live_values' => '{"gateway":"fatoorah","mode":"test","status":"0","api_key":"data"}',
                'test_values' => '{"gateway":"fatoorah","mode":"test","status":"0","api_key":"data"}',
                'settings_type' => 'payment_config',
                'mode' => 'test',
                'is_active' => 0,
                'created_at' => null,
                'updated_at' => '2023-08-12 06:36:24',
                'additional_data' => '{"gateway_title":null,"gateway_image":""}',
            ],
            [
                'id' => '58c1bc8a-d6ac-11ed-962c-0c7a158e4469',
                'key_name' => 'ccavenue',
                'live_values' => '{"gateway":"ccavenue","mode":"test","status":"0","merchant_id":"data","working_key":"data","access_code":"data"}',
                'test_values' => '{"gateway":"ccavenue","mode":"test","status":"0","merchant_id":"data","working_key":"data","access_code":"data"}',
                'settings_type' => 'payment_config',
                'mode' => 'test',
                'is_active' => 0,
                'created_at' => null,
                'updated_at' => '2023-08-30 03:42:38',
                'additional_data' => '{"gateway_title":null,"gateway_image":"2023-04-13-643783f01d386.png"}',
            ],
            [
                'id' => '5e2d2ef9-d6ab-11ed-962c-0c7a158e4469',
                'key_name' => 'thawani',
                'live_values' => '{"gateway":"thawani","mode":"test","status":"0","public_key":"data","private_key":"data"}',
                'test_values' => '{"gateway":"thawani","mode":"test","status":"0","public_key":"data","private_key":"data"}',
                'settings_type' => 'payment_config',
                'mode' => 'test',
                'is_active' => 0,
                'created_at' => null,
                'updated_at' => '2023-08-30 04:50:40',
                'additional_data' => '{"gateway_title":null,"gateway_image":"2023-04-13-64378f9856f29.png"}',
            ],
            [
                'id' => '60cc83cc-d5b9-11ed-b56f-0c7a158e4469',
                'key_name' => 'sixcash',
                'live_values' => '{"gateway":"sixcash","mode":"test","status":"0","public_key":"data","secret_key":"data","merchant_number":"data","base_url":"data"}',
                'test_values' => '{"gateway":"sixcash","mode":"test","status":"0","public_key":"data","secret_key":"data","merchant_number":"data","base_url":"data"}',
                'settings_type' => 'payment_config',
                'mode' => 'test',
                'is_active' => 0,
                'created_at' => null,
                'updated_at' => '2023-08-30 04:16:17',
                'additional_data' => '{"gateway_title":null,"gateway_image":"2023-04-12-6436774e77ff9.png"}',
            ],
            [
                'id' => '68579846-d8e8-11ed-8249-0c7a158e4469',
                'key_name' => 'alphanet_sms',
                'live_values' => '{"gateway":"alphanet_sms","mode":"live","status":0,"api_key":"","otp_template":""}',
                'test_values' => '{"gateway":"alphanet_sms","mode":"live","status":0,"api_key":"","otp_template":""}',
                'settings_type' => 'sms_config',
                'mode' => 'live',
                'is_active' => 0,
                'created_at' => null,
                'updated_at' => null,
                'additional_data' => null,
            ],
            [
                'id' => '6857a2e8-d8e8-11ed-8249-0c7a158e4469',
                'key_name' => 'sms_to',
                'live_values' => '{"gateway":"sms_to","mode":"live","status":0,"api_key":"","sender_id":"","otp_template":""}',
                'test_values' => '{"gateway":"sms_to","mode":"live","status":0,"api_key":"","sender_id":"","otp_template":""}',
                'settings_type' => 'sms_config',
                'mode' => 'live',
                'is_active' => 0,
                'created_at' => null,
                'updated_at' => null,
                'additional_data' => null,
            ],
            [
                'id' => '74c30c00-d6a6-11ed-962c-0c7a158e4469',
                'key_name' => 'hubtel',
                'live_values' => '{"gateway":"hubtel","mode":"test","status":"0","account_number":"data","api_id":"data","api_key":"data"}',
                'test_values' => '{"gateway":"hubtel","mode":"test","status":"0","account_number":"data","api_id":"data","api_key":"data"}',
                'settings_type' => 'payment_config',
                'mode' => 'test',
                'is_active' => 0,
                'created_at' => null,
                'updated_at' => '2023-08-12 06:37:43',
                'additional_data' => '{"gateway_title":null,"gateway_image":""}',
            ],
            [
                'id' => '74e46b0a-d6aa-11ed-962c-0c7a158e4469',
                'key_name' => 'tap',
                'live_values' => '{"gateway":"tap","mode":"test","status":"0","secret_key":"data"}',
                'test_values' => '{"gateway":"tap","mode":"test","status":"0","secret_key":"data"}',
                'settings_type' => 'payment_config',
                'mode' => 'test',
                'is_active' => 0,
                'created_at' => null,
                'updated_at' => '2023-08-30 04:50:09',
                'additional_data' => '{"gateway_title":null,"gateway_image":""}',
            ],
            [
                'id' => '761ca96c-d1eb-11ed-87ca-0c7a158e4469',
                'key_name' => 'swish',
                'live_values' => '{"gateway":"swish","mode":"test","status":"0","number":"data"}',
                'test_values' => '{"gateway":"swish","mode":"test","status":"0","number":"data"}',
                'settings_type' => 'payment_config',
                'mode' => 'test',
                'is_active' => 0,
                'created_at' => null,
                'updated_at' => '2023-08-30 04:17:02',
                'additional_data' => '{"gateway_title":null,"gateway_image":""}',
            ],
            [
                'id' => '7b1c3c5f-d2bd-11ed-b485-0c7a158e4469',
                'key_name' => 'payfast',
                'live_values' => '{"gateway":"payfast","mode":"test","status":"0","merchant_id":"data","secured_key":"data"}',
                'test_values' => '{"gateway":"payfast","mode":"test","status":"0","merchant_id":"data","secured_key":"data"}',
                'settings_type' => 'payment_config',
                'mode' => 'test',
                'is_active' => 0,
                'created_at' => null,
                'updated_at' => '2023-08-30 04:18:13',
                'additional_data' => '{"gateway_title":null,"gateway_image":""}',
            ],
            [
                'id' => '8592417b-d1d1-11ed-a984-0c7a158e4469',
                'key_name' => 'esewa',
                'live_values' => '{"gateway":"esewa","mode":"test","status":"0","merchantCode":"data"}',
                'test_values' => '{"gateway":"esewa","mode":"test","status":"0","merchantCode":"data"}',
                'settings_type' => 'payment_config',
                'mode' => 'test',
                'is_active' => 0,
                'created_at' => null,
                'updated_at' => '2023-08-30 04:17:38',
                'additional_data' => '{"gateway_title":null,"gateway_image":""}',
            ],
            [
                'id' => '9162a1dc-cdf1-11ed-affe-0c7a158e4469',
                'key_name' => 'viva_wallet',
                'live_values' => '{"gateway":"viva_wallet","mode":"test","status":"0","client_id": "","client_secret": "", "source_code":""}',
                'test_values' => '{"gateway":"viva_wallet","mode":"test","status":"0","client_id": "","client_secret": "", "source_code":""}',
                'settings_type' => 'payment_config',
                'mode' => 'test',
                'is_active' => 0,
                'created_at' => null,
                'updated_at' => null,
                'additional_data' => null,
            ],
            [
                'id' => '998ccc62-d6a0-11ed-962c-0c7a158e4469',
                'key_name' => 'stripe',
                'live_values' => '{"gateway":"stripe","mode":"test","status":"1","api_key":"data","published_key":"data"}',
                'test_values' => '{"gateway":"stripe","mode":"test","status":"1","api_key":"data","published_key":"data"}',
                'settings_type' => 'payment_config',
                'mode' => 'test',
                'is_active' => 1,
                'created_at' => null,
                'updated_at' => '2023-08-30 04:18:55',
                'additional_data' => '{"gateway_title":null,"gateway_image":"2023-08-10-64d4bc2bb983a.png"}',
            ],
            [
                'id' => 'a3313755-c95d-11ed-b1db-0c7a158e4469',
                'key_name' => 'iyzi_pay',
                'live_values' => '{"gateway":"iyzi_pay","mode":"test","status":"0","api_key":"data","secret_key":"data","base_url":"data"}',
                'test_values' => '{"gateway":"iyzi_pay","mode":"test","status":"0","api_key":"data","secret_key":"data","base_url":"data"}',
                'settings_type' => 'payment_config',
                'mode' => 'test',
                'is_active' => 0,
                'created_at' => null,
                'updated_at' => '2023-08-30 04:20:02',
                'additional_data' => '{"gateway_title":null,"gateway_image":""}',
            ],
            [
                'id' => 'a76c8993-d299-11ed-b485-0c7a158e4469',
                'key_name' => 'momo',
                'live_values' => '{"gateway":"momo","mode":"live","status":"0","api_key":"data","api_user":"data","subscription_key":"data"}',
                'test_values' => '{"gateway":"momo","mode":"live","status":"0","api_key":"data","api_user":"data","subscription_key":"data"}',
                'settings_type' => 'payment_config',
                'mode' => 'live',
                'is_active' => 0,
                'created_at' => null,
                'updated_at' => '2023-08-30 04:19:28',
                'additional_data' => '{"gateway_title":null,"gateway_image":""}',
            ],
            [
                'id' => 'a8608119-cc76-11ed-9bca-0c7a158e4469',
                'key_name' => 'moncash',
                'live_values' => '{"gateway":"moncash","mode":"test","status":"0","client_id":"data","secret_key":"data"}',
                'test_values' => '{"gateway":"moncash","mode":"test","status":"0","client_id":"data","secret_key":"data"}',
                'settings_type' => 'payment_config',
                'mode' => 'test',
                'is_active' => 0,
                'created_at' => null,
                'updated_at' => '2023-08-30 04:47:34',
                'additional_data' => '{"gateway_title":null,"gateway_image":""}',
            ],
            [
                'id' => 'ad5af1c1-d6a2-11ed-962c-0c7a158e4469',
                'key_name' => 'razor_pay',
                'live_values' => '{"gateway":"razor_pay","mode":"test","status":"1","api_key":"data","api_secret":"data"}',
                'test_values' => '{"gateway":"razor_pay","mode":"test","status":"1","api_key":"data","api_secret":"data"}',
                'settings_type' => 'payment_config',
                'mode' => 'test',
                'is_active' => 1,
                'created_at' => null,
                'updated_at' => '2023-08-30 04:47:00',
                'additional_data' => '{"gateway_title":null,"gateway_image":"2023-08-10-64d4bbeecee6c.png"}',
            ],
            [
                'id' => 'ad5b02a0-d6a2-11ed-962c-0c7a158e4469',
                'key_name' => 'senang_pay',
                'live_values' => '{"gateway":"senang_pay","mode":"test","status":"0","callback_url":"data","secret_key":"data","merchant_id":"data"}',
                'test_values' => '{"gateway":"senang_pay","mode":"test","status":"0","callback_url":"data","secret_key":"data","merchant_id":"data"}',
                'settings_type' => 'payment_config',
                'mode' => 'test',
                'is_active' => 0,
                'created_at' => null,
                'updated_at' => '2023-08-27 09:58:57',
                'additional_data' => '{"gateway_title":"data","gateway_image":""}',
            ],
            [
                'id' => 'b6c333f6-d8e9-11ed-8249-0c7a158e4469',
                'key_name' => 'akandit_sms',
                'live_values' => '{"gateway":"akandit_sms","mode":"live","status":0,"username":"","password":"","otp_template":""}',
                'test_values' => '{"gateway":"akandit_sms","mode":"live","status":0,"username":"","password":"","otp_template":""}',
                'settings_type' => 'sms_config',
                'mode' => 'live',
                'is_active' => 0,
                'created_at' => null,
                'updated_at' => null,
                'additional_data' => null,
            ],
            [
                'id' => 'b6c33c87-d8e9-11ed-8249-0c7a158e4469',
                'key_name' => 'global_sms',
                'live_values' => '{"gateway":"global_sms","mode":"live","status":0,"user_name":"","password":"","from":"","otp_template":""}',
                'test_values' => '{"gateway":"global_sms","mode":"live","status":0,"user_name":"","password":"","from":"","otp_template":""}',
                'settings_type' => 'sms_config',
                'mode' => 'live',
                'is_active' => 0,
                'created_at' => null,
                'updated_at' => null,
                'additional_data' => null,
            ],
            [
                'id' => 'b8992bd4-d6a0-11ed-962c-0c7a158e4469',
                'key_name' => 'paymob',
                'live_values' => '{"gateway":"paymob","mode":"live","status":"0","api_key":"","iframe_id":"","integration_id":"","hmac":"","callback_url":""}',
                'test_values' => '{"gateway":"paymob","mode":"live","status":"0","api_key":"","iframe_id":"","integration_id":"","hmac":"","callback_url":""}',
                'settings_type' => 'payment_config',
                'mode' => 'test',
                'is_active' => 0,
                'created_at' => null,
                'updated_at' => null,
                'additional_data' => null,
            ],
            [
                'id' => 'c41c0dcd-d119-11ed-9f67-0c7a158e4469',
                'key_name' => 'maxicash',
                'live_values' => '{"gateway":"maxicash","mode":"test","status":"0","merchantId":"data","merchantPassword":"data"}',
                'test_values' => '{"gateway":"maxicash","mode":"test","status":"0","merchantId":"data","merchantPassword":"data"}',
                'settings_type' => 'payment_config',
                'mode' => 'test',
                'is_active' => 0,
                'created_at' => null,
                'updated_at' => '2023-08-30 04:49:15',
                'additional_data' => '{"gateway_title":null,"gateway_image":""}',
            ],
            [
                'id' => 'c9249d17-cd60-11ed-b879-0c7a158e4469',
                'key_name' => 'pvit',
                'live_values' => '{"gateway":"pvit","mode":"test","status":"0","mc_tel_merchant": "","access_token": "", "mc_merchant_code": ""}',
                'test_values' => '{"gateway":"pvit","mode":"test","status":"0","mc_tel_merchant": "","access_token": "", "mc_merchant_code": ""}',
                'settings_type' => 'payment_config',
                'mode' => 'test',
                'is_active' => 0,
                'created_at' => null,
                'updated_at' => null,
                'additional_data' => null,
            ],
            [
                'id' => 'cb0081ce-d775-11ed-96f4-0c7a158e4469',
                'key_name' => 'releans',
                'live_values' => '{"gateway":"releans","mode":"live","status":0,"api_key":"","from":"","otp_template":""}',
                'test_values' => '{"gateway":"releans","mode":"live","status":0,"api_key":"","from":"","otp_template":""}',
                'settings_type' => 'sms_config',
                'mode' => 'live',
                'is_active' => 0,
                'created_at' => null,
                'updated_at' => '2023-04-10 02:14:44',
                'additional_data' => null,
            ],
            [
                'id' => 'd4f3f5f1-d6a0-11ed-962c-0c7a158e4469',
                'key_name' => 'flutterwave',
                'live_values' => '{"gateway":"flutterwave","mode":"test","status":"1","secret_key":"data","public_key":"data","hash":"data"}',
                'test_values' => '{"gateway":"flutterwave","mode":"test","status":"1","secret_key":"data","public_key":"data","hash":"data"}',
                'settings_type' => 'payment_config',
                'mode' => 'test',
                'is_active' => 1,
                'created_at' => null,
                'updated_at' => '2023-08-30 04:41:03',
                'additional_data' => '{"gateway_title":null,"gateway_image":"2023-08-22-64e4439f95a8b.png"}',
            ],
            [
                'id' => 'd822f1a5-c864-11ed-ac7a-0c7a158e4469',
                'key_name' => 'paystack',
                'live_values' => '{"gateway":"paystack","mode":"test","status":"1","public_key":"data","secret_key":"data","merchant_email":"data"}',
                'test_values' => '{"gateway":"paystack","mode":"test","status":"1""public_key":"data","secret_key":"data","merchant_email":"data"}',
                'settings_type' => 'payment_config',
                'mode' => 'test',
                'is_active' => 1,
                'created_at' => null,
                'updated_at' => '2023-08-30 04:20:45',
                'additional_data' => '{"gateway_title":null,"gateway_image":"2023-08-10-64d4bb67d6345.png"}',
            ],
            [
                'id' => 'daec8d59-c893-11ed-ac7a-0c7a158e4469',
                'key_name' => 'xendit',
                'live_values' => '{"gateway":"xendit","mode":"test","status":"0","api_key":"data"}',
                'test_values' => '{"gateway":"xendit","mode":"test","status":"0","api_key":"data"}',
                'settings_type' => 'payment_config',
                'mode' => 'test',
                'is_active' => 0,
                'created_at' => null,
                'updated_at' => '2023-08-12 06:35:46',
                'additional_data' => '{"gateway_title":null,"gateway_image":""}',
            ],
            [
                'id' => 'dc0f5fc9-d6a5-11ed-962c-0c7a158e4469',
                'key_name' => 'worldpay',
                'live_values' => '{"gateway":"worldpay","mode":"test","status":"0","OrgUnitId":"data","jwt_issuer":"data","mac":"data","merchantCode":"data","xml_password":"data"}',
                'test_values' => '{"gateway":"worldpay","mode":"test","status":"0","OrgUnitId":"data","jwt_issuer":"data","mac":"data","merchantCode":"data","xml_password":"data"}',
                'settings_type' => 'payment_config',
                'mode' => 'test',
                'is_active' => 0,
                'created_at' => null,
                'updated_at' => '2023-08-12 06:35:26',
                'additional_data' => '{"gateway_title":null,"gateway_image":""}',
            ],
            [
                'id' => 'e0450278-d8eb-11ed-8249-0c7a158e4469',
                'key_name' => 'signal_wire',
                'live_values' => '{"gateway":"signal_wire","mode":"live","status":0,"project_id":"","token":"","space_url":"","from":"","otp_template":""}',
                'test_values' => '{"gateway":"signal_wire","mode":"live","status":0,"project_id":"","token":"","space_url":"","from":"","otp_template":""}',
                'settings_type' => 'sms_config',
                'mode' => 'live',
                'is_active' => 0,
                'created_at' => null,
                'updated_at' => null,
                'additional_data' => null,
            ],
            [
                'id' => 'e0450b40-d8eb-11ed-8249-0c7a158e4469',
                'key_name' => 'paradox',
                'live_values' => '{"gateway":"paradox","mode":"live","status":0,"api_key":""}',
                'test_values' => '{"gateway":"paradox","mode":"live","status":0,"api_key":""}',
                'settings_type' => 'sms_config',
                'mode' => 'live',
                'is_active' => 0,
                'created_at' => null,
                'updated_at' => null,
                'additional_data' => null,
            ],
            [
                'id' => 'ea346efe-cdda-11ed-affe-0c7a158e4469',
                'key_name' => 'ssl_commerz',
                'live_values' => '{"gateway":"ssl_commerz","mode":"test","status":"0","store_id":"data","store_password":"data"}',
                'test_values' => '{"gateway":"ssl_commerz","mode":"test","status":"0","store_id":"data","store_password":"data"}',
                'settings_type' => 'payment_config',
                'mode' => 'test',
                'is_active' => 0,
                'created_at' => null,
                'updated_at' => '2023-08-30 03:43:49',
                'additional_data' => '{"gateway_title":null,"gateway_image":"2023-08-20-64e1ec1fb1730.png"}',
            ],
            [
                'id' => 'eed88336-d8ec-11ed-8249-0c7a158e4469',
                'key_name' => 'hubtel',
                'live_values' => '{"gateway":"hubtel","mode":"live","status":0,"sender_id":"","client_id":"","client_secret":"","otp_template":""}',
                'test_values' => '{"gateway":"hubtel","mode":"live","status":0,"sender_id":"","client_id":"","client_secret":"","otp_template":""}',
                'settings_type' => 'sms_config',
                'mode' => 'live',
                'is_active' => 0,
                'created_at' => null,
                'updated_at' => null,
                'additional_data' => null,
            ],
            [
                'id' => 'f149c546-d8ea-11ed-8249-0c7a158e4469',
                'key_name' => 'viatech',
                'live_values' => '{"gateway":"viatech","mode":"live","status":0,"api_url":"","api_key":"","sender_id":"","otp_template":""}',
                'test_values' => '{"gateway":"viatech","mode":"live","status":0,"api_url":"","api_key":"","sender_id":"","otp_template":""}',
                'settings_type' => 'sms_config',
                'mode' => 'live',
                'is_active' => 0,
                'created_at' => null,
                'updated_at' => null,
                'additional_data' => null,
            ],
            [
                'id' => 'f149cd9c-d8ea-11ed-8249-0c7a158e4469',
                'key_name' => '019_sms',
                'live_values' => '{"gateway":"019_sms","mode":"live","status":0,"password":"","username":"","username_for_token":"","sender":"","otp_template":""}',
                'test_values' => '{"gateway":"019_sms","mode":"live","status":0,"password":"","username":"","username_for_token":"","sender":"","otp_template":""}',
                'settings_type' => 'sms_config',
                'mode' => 'live',
                'is_active' => 1,
                'created_at' => null,
                'updated_at' => null,
                'additional_data' => null,
            ],
        ];

        DB::table('addon_settings')->insertOrIgnore($settings);
    }
}