<?php

use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
       DB::table('business_settings')->insertOrIgnore([
            ['key' => 'wallet_daily_top_up_limit', 'value' => '50000'],
            ['key' => 'wallet_daily_transfer_limit', 'value' => '25000'],
            ['key' => 'wallet_monthly_top_up_limit', 'value' => '500000'],
            ['key' => 'wallet_monthly_transfer_limit', 'value' => '250000'],
            ['key' => 'wallet_min_transfer_amount', 'value' => '1'],
            ['key' => 'wallet_max_transfer_amount', 'value' => '5000'],
            ['key' => 'wallet_min_top_up_amount', 'value' => '1'],
            ['key' => 'wallet_max_top_up_amount', 'value' => '50000'],
            ['key' => 'wallet_transfer_fee_percentage', 'value' => '0'],
            ['key' => 'wallet_transfer_fee_fixed', 'value' => '0'],
            ['key' => 'wallet_top_up_bonus_percentage', 'value' => '0'],
            ['key' => 'wallet_otp_expiry_minutes', 'value' => '5'],
            ['key' => 'wallet_pin_max_attempts', 'value' => '3'],
            ['key' => 'wallet_enabled', 'value' => '1'],
            ['key' => 'wallet_two_factor_enabled', 'value' => '0'],
            ['key' => 'qib_bank_enabled', 'value' => '1'],
            ['key' => 'restaurant_open_time', 'value' => null],
            ['key' => 'restaurant_close_time', 'value' => null],
            ['key' => 'restaurant_name', 'value' => 'dinehub'],
            ['key' => 'currency', 'value' => 'USD'],
            ['key' => 'logo', 'value' => '2024-07-11-668efdc7ca05e.png'],
            ['key' => 'mail_config', 'value' => '{"status":1,"name":"Delivery APP","host":"smtp.hostinger.com","driver":"smtp","port":"465","username":"efood@modernhome-ye.com","email_id":"efood@modernhome-ye.com","encryption":"tls","password":"E@food_root10500"}'],
            ['key' => 'delivery_charge', 'value' => '0'],
            ['key' => 'phone', 'value' => '+44 7388 024469'],
            [
                'key'   => 'footer_text',
                'value' => 'Copyright © ' . date('Y') . ' All rights reserved.',
            ],
            ['key' => 'address', 'value' => "This address is for demonstration purposes only. You can insert your restaurant or business address here as needed.\r\nExample:\r\n71-75 Shelton Street,\r\nCovent Garden, London,\r\nWC2H 9JQ, United Kingdom\r\nEmail: info@ecoretechco.com\r\nWebsite: www.ecoretechco.com\r\nYou can purchase this version from Ecore Techco LTD."],
            ['key' => 'email_address', 'value' => 'support@ecoretechco.com'],
            ['key' => 'cash_on_delivery', 'value' => '{"status":"1"}'],
            ['key' => 'email_verification', 'value' => null],
            ['key' => 'digital_payment', 'value' => '{"status":"1"}'],
            ['key' => 'terms_and_conditions', 'value' => '<p>Terms and Conditions – الشروط والأحكام</p><p><br></p><p><br></p><p>نموذج توضيحي للشروط، قابل للتعديل حسب طبيعة عمل مطعمكم.</p><p>من خلال استخدام هذا الموقع أو التطبيق، يوافق المستخدم على الشروط والأحكام المتعلقة بالطلبات، الدفع، الخدمة، والتوصيل.</p><p><br></p><p><br></p><p><br></p><p>This is a sample of the terms and conditions, customizable to your business needs.</p><ol><li>By using this website or application, users agree to the terms regarding orders, payments, services, and deliveries.</li></ol>'],
            ['key' => 'fcm_topic', 'value' => ''],
            ['key' => 'fcm_project_id', 'value' => '3f34f34'],
            ['key' => 'push_notification_key', 'value' => 'demo'],
            ['key' => 'order_pending_message', 'value' => '{"status":1,"message":"Your order has been placed successfully."}'],
            ['key' => 'order_processing_message', 'value' => '{"status":1,"message":"Your order is going to the cook"}'],
            ['key' => 'out_for_delivery_message', 'value' => '{"status":1,"message":"Order out for delivery."}'],
            ['key' => 'order_delivered_message', 'value' => '{"status":1,"message":"delivered"}'],
            ['key' => 'delivery_boy_assign_message', 'value' => '{"status":1,"message":"boy assigned"}'],
            ['key' => 'delivery_boy_start_message', 'value' => '{"status":1,"message":"start delivery"}'],
            ['key' => 'delivery_boy_delivered_message', 'value' => '{"status":1,"message":"boy delivered"}'],
            ['key' => 'order_confirmation_msg', 'value' => '{"status":1,"message":"Your order has been confirmed."}'],
            ['key' => 'razor_pay', 'value' => '{"status":"0","razor_key":null,"razor_secret":null}'],
            ['key' => 'location_coverage', 'value' => '{"status":1,"longitude":"91.410747","latitude":"22.986282","coverage":"20"}'],
            ['key' => 'minimum_order_value', 'value' => '50'],
            ['key' => 'point_per_currency', 'value' => null],
            ['key' => 'internal_point', 'value' => '{"status":null}'],
            ['key' => 'senang_pay', 'value' => '{"status":"0","secret_key":null,"merchant_id":null}'],
            ['key' => 'privacy_policy', 'value' => '<p><strong>Privacy Policy – سياسة الخصوصية</strong></p><p> </p><p><br></p><p>سياسة افتراضية توضح كيفية التعامل مع البيانات، قابلة للتخصيص.</p><p>نحن نحترم خصوصيتكم وملتزمون بحماية بياناتكم الشخصية. سيتم توضيح كيف ومتى ولماذا نجمع المعلومات.</p><p><br></p><p> </p><p><br></p><p>Sample privacy policy outlining data use and protection, customizable as needed.</p><p>We respect your privacy and are committed to protecting your personal information. This section explains how, when, and why we collect and use your data.</p>'],
            ['key' => 'about_us', 'value' => '<p>هذه الصفحة توضح معلومات عامة عن مطعمكم ويمكن تخصيصها بالكامل حسب طلبكم.</p><p>نظام DineHub هو منصة ذكية لإدارة المطاعم وتوصيل الطلبات، تم تطويرها بواسطة شركة Ecore Techco LTD، لتقديم حلول مبتكرة تواكب تطلعات أصحاب المطاعم وتمنحهم تجربة إدارة فعالة وشاملة.</p><p>نحن نؤمن بأن التكنولوجيا هي مفتاح النمو، ونهدف إلى تمكينكم من تحويل أفكاركم إلى واقع ملموس من خلال أدوات رقمية متطورة وسهلة الاستخدام.</p><p>ملاحظة: جميع الأقسام والمنتجات المعروضة في هذا الموقع هي وهمية لأغراض العرض والتجربة فقط، ويمكن تعديلها أو تخصيصها بالكامل حسب طلبكم.</p><p><br></p><p>يمكنك شراء هذه النسخة من Ecore Techco LTD، وهي شركة محدودة مسجلة في إنجلترا، المملكة المتحدة تحت رقم الشركة 14140130.</p><p>البريد الإلكتروني: info@ecoretechco.com</p><p>الموقع الإلكتروني: www.ecoretechco.com</p><p><br></p>This is a placeholder page and can be fully customized to reflect your brand.</p><p>DineHub is an advanced platform for restaurant and delivery management, developed by Ecore Techco LTD. It’s designed to offer innovative solutions that meet the expectations of restaurant owners and provide a complete, seamless management experience.</p><p>We believe that technology is the key to growth, and our goal is to help you turn your ideas into reality through powerful, user-friendly digital tools.</p><p>Note: All sections and products displayed on this site are fictional and intended for demo and preview purposes only. They can be updated and customized according to your needs.</p><p><br></p><p>You can purchase this version from Ecore Techco LTD, a limited company registered in England, UK under company number 14140130.</p><p>Email: info@ecoretechco.com</p><p>Website: www.ecoretechco.com</p><p><br></p>'],
            ['key' => 'time_zone', 'value' => 'Africa/Cairo'],
            ['key' => 'maintenance_mode', 'value' => '0'],
            ['key' => 'currency_symbol_position', 'value' => 'right'],
            ['key' => 'language', 'value' => '[{"id":1,"name":"en","direction":"ltr","code":"en","status":1,"default":false},{"id":2,"name":"Arabic","direction":"ltr","code":"ar","status":1,"default":true}]'],
            ['key' => 'self_pickup', 'value' => '1'],
            ['key' => 'delivery', 'value' => '1'],
            ['key' => 'phone_verification', 'value' => null],
            ['key' => 'pagination_limit', 'value' => '10'],
            ['key' => 'map_api_key', 'value' => ''],
            ['key' => 'delivery_management', 'value' => '{"status":0,"min_shipping_charge":0,"shipping_per_km":0}'],
            ['key' => 'paymob', 'value' => '{"status":"1","api_key":"","iframe_id":"","integration_id":"","hmac":""}'],
            ['key' => 'qib', 'value' => '{"status":"1","api_key":"","iframe_id":"","integration_id":"","hmac":""}'],
            ['key' => 'returned_message', 'value' => '{"status":0,"message":null}'],
            ['key' => 'failed_message', 'value' => '{"status":0,"message":null}'],
            ['key' => 'canceled_message', 'value' => '{"status":0,"message":null}'],
            ['key' => 'recaptcha', 'value' => '{"status":"1","site_key":null,"secret_key":null}'],
            ['key' => 'firestore_db', 'value' => '{"apiKey":"","authDomain":"","projectId":"","storageBucket":"","messagingSenderId":"","appId":""}'],
            ['key' => 'play_store_config', 'value' => '{"status":"","link":"","min_version":"1"}'],
            ['key' => 'app_store_config', 'value' => '{"status":"","link":"","min_version":"1"}'],
            ['key' => 'default_preparation_time', 'value' => '30'],
            ['key' => 'decimal_point_settings', 'value' => '2'],
            ['key' => 'schedule_order_slot_duration', 'value' => '1'],
            ['key' => 'time_format', 'value' => '24'],
            ['key' => 'wallet_status', 'value' => '1'],
            ['key' => 'loyalty_point_status', 'value' => '1'],
            ['key' => 'ref_earning_status', 'value' => '1'],
            ['key' => 'loyalty_point_exchange_rate', 'value' => '5'],
            ['key' => 'ref_earning_exchange_rate', 'value' => '1'],
            ['key' => 'loyalty_point_item_purchase_point', 'value' => '3'],
            ['key' => 'loyalty_point_minimum_point', 'value' => '1'],
            ['key' => 'whatsapp', 'value' => '{"status":1,"number":"778511119"}'],
            ['key' => 'fav_icon', 'value' => '2024-07-11-668efdc7cb05a.png'],
            ['key' => 'cookies', 'value' => '{"status":"1","text":"Cookie Policy – سياسة ملفات تعريف الارتباط... (full text from your dump)"}'],
            ['key' => 'maximum_otp_hit', 'value' => '5'],
            ['key' => 'otp_resend_time', 'value' => '60'],
            ['key' => 'temporary_block_time', 'value' => '600'],
            ['key' => 'dm_self_registration', 'value' => '1'],
            ['key' => 'toggle_veg_non_veg', 'value' => '1'],
            ['key' => 'maximum_login_hit', 'value' => '5'],
            ['key' => 'temporary_login_block_time', 'value' => '600'],
            ['key' => 'return_page', 'value' => '{"status":0,"content":"<p><strong>Return Policy..."}'],
            ['key' => 'refund_page', 'value' => '{"status":0,"content":"<p><strong>Refund Policy..."}'],
            ['key' => 'cancellation_page', 'value' => '{"status":0,"content":"<p><strong>Cancellation Policy..."}'],
            ['key' => 'offline_payment', 'value' => '{"status":"1"}'],
            ['key' => 'guest_checkout', 'value' => '1'],
            ['key' => 'partial_payment', 'value' => '1'],
            ['key' => 'partial_payment_combine_with', 'value' => 'all'],
            ['key' => 'apple_login', 'value' => '{"login_medium":"apple","client_id":"","client_secret":"","team_id":"","key_id":"","service_file":"","redirect_url":"","status":0}'],
            ['key' => 'add_wallet_message', 'value' => '{"status":0,"message":null}'],
            ['key' => 'add_wallet_bonus_message', 'value' => '{"status":1,"message":"عزيزي العميل لقد تم إضافة مبلغ هدية لك"}'],
            ['key' => 'firebase_otp_verification', 'value' => '{"status":0,"web_api_key":""}'],
            ['key' => 'footer_description_text', 'value' => 'dinehub'],
            ['key' => 'push_notification_service_file_content', 'value' => json_encode(json_decode('{"type":"service_account","project_id":"fareda-f2dc7",... (your full JSON)'), true)],
            ['key' => 'country', 'value' => 'EG'],
            ['key' => 'app_activation', 'value' => '[{"software_id":"40488338","is_active":1},{"software_id":"40488202","is_active":1}]'],
            ['key' => 'google_map_status', 'value' => '1'],
            ['key' => 'admin_order_notification', 'value' => '1'],
            ['key' => 'admin_order_notification_type', 'value' => 'firebase'],
            ['key' => 'wallet_topup_email_status_user', 'value' => '1'],
            ['key' => 'wallet_topup_whatsapp_status_user', 'value' => '1'],
            ['key' => 'maintenance_duration_setup', 'value' => json_encode([
                'maintenance_duration' => 'until_change',
                'start_date' => null,
                'end_date' => null
            ])],
            ['key' => 'maintenance_system_setup', 'value' => json_encode([])],
            ['key' => 'maintenance_message_setup', 'value' => json_encode([
                'business_number' => 0,
                'business_email' => 0,
                'maintenance_message' => '',
                'message_body' => ''
            ])],
            ['key' => 'customer_notify_message', 'value' => '{"status":0,"message":null}'],
            ['key' => 'customer_notify_message_for_time_change', 'value' => '{"status":0,"message":null}'],
            ['key' => 'cutlery_status', 'value' => '0'],
            ['key' => 'add_fund_to_wallet', 'value' => '0'],
            ['key' => 'fcm_credentials', 'value' => json_encode([
                'apiKey' => '',
                'authDomain' => '',
                'projectId' => '',
                'storageBucket' => '',
                'messagingSenderId' => '',
                'appId' => '',
                'measurementId' => ''
            ])],
            ['key' => 'map_api_server_key', 'value' => ''],
            ['key' => 'map_api_client_key', 'value' => ''],
            ['key' => 'search_placeholder', 'value' => json_encode([])],
            ['key' => 'meta_pixel', 'value' => json_encode([
                'status' => 0,
                'meta_app_id' => ''
            ])],
            ['key' => 'place_order_mail_status_user', 'value' => '1'],
            ['key' => 'forget_password_mail_status_user', 'value' => '1'],
            ['key' => 'registration_otp_mail_status_user', 'value' => '1'],
        ]);
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        DB::table('business_settings')->whereIn('key', [
            'wallet_daily_top_up_limit',
            'wallet_daily_transfer_limit',
            'wallet_monthly_top_up_limit',
            'wallet_monthly_transfer_limit',
            'wallet_min_transfer_amount',
            'wallet_max_transfer_amount',
            'wallet_min_top_up_amount',
            'wallet_max_top_up_amount',
            'wallet_transfer_fee_percentage',
            'wallet_transfer_fee_fixed',
            'wallet_top_up_bonus_percentage',
            'wallet_otp_expiry_minutes',
            'wallet_pin_max_attempts',
            'wallet_enabled',
            'wallet_two_factor_enabled',
            'paytabs_enabled',
            'paypal_enabled',
            'qib_bank_enabled',
            'stripe_enabled',
            'flutterwave_enabled',
            'paystack_enabled',
            'restaurant_open_time',
            'restaurant_close_time',
            'restaurant_name',
            'currency',
            'logo',
            'mail_config',
            'delivery_charge',
            'ssl_commerz_payment',
            'paypal',
            'stripe',
            'phone',
            'footer_text',
            'address',
            'email_address',
            'cash_on_delivery',
            'email_verification',
            'digital_payment',
            'terms_and_conditions',
            'fcm_topic',
            'fcm_project_id',
            'push_notification_key',
            'order_pending_message',
            'order_processing_message',
            'out_for_delivery_message',
            'order_delivered_message',
            'wallet_topup_email_status_user',
            'wallet_topup_whatsapp_status_user',
        ])->delete();
    }
};
